name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      # validate that the gradle wrapper matches official checksums.
      - uses: gradle/wrapper-validation-action@v3

      - name: Build and Publish with Gradle
        run: |
          ./gradlew build