name: Gradle Release

on:
  push:
    tags:
      - releases/*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and Publish with Gradle
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/releases/}
          echo "Tag name: $TAG_NAME"
          ./gradlew publish --no-daemon --info -PreleaseVersion=$TAG_NAME
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}